### ISSUE TITLE
Edit Expense

### ISSUE THREAD

**Issue by ChristianMoschke** [miToe/dagobert#10]
## Value proposition
As a **budget-conscious user**, 
I want to **be able to edit the details of an expense**, 
so that **I can correct any mistakes or update the information for better tracking**.
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] In the expense detail view (from the previous user story), there should be an "Edit" button.

-------------------------------------------------------------------------------------------------

#### Clicking the "Edit" button allows the user to modify the existing information of the expense, such as:

- [ ] Date
- [ ] Amount
- [ ] Category
- [ ] Description
- [ ] Payment method (if applicable)

-------------------------------------------------------------------------------------------------

- [ ] After making changes, the user should be able to save the edits to update the expense record.
- [ ] The edited information should be reflected in the expense list view.
- [ ] The system should display a confirmation message upon successful edit to inform the user.

## Tasks
- [ ] List the tasks that need to be performed within the dev team #
