### ISSUE TITLE
Search Transactions

### ISSUE THREAD

**Issue by ChristianMoschke** [miToe/dagobert#12]
## Value proposition
As a **budget-conscious user**, 
I want to be able to **search my expense list by date, category, and payment method**, 
so that **I can easily find specific transactions and analyze my spending habits in more detail**.
## Description
![Image](https://github.com/miToe/dagobert/assets/164089597/b569fa9b-c4a9-457b-9110-81fd0db934cd)

## Acceptance criteria
- [ ] Users can enter keywords (e.g., restaurant name) to search for expenses containing those keywords in the description field (if provided).
- [ ] The search should be applied in real-time, dynamically filtering the expense list based on the entered keywords.
- [ ] Real-time search with auto-suggestions
- [ ] Clearable input
- [ ] Clearing the search bar should reset the expense list view to show all entries.
- [ ] Not case sensitive
- [ ] Ignore white space

- [ ] Satisfies [Styling Ticket](https://github.com/miToe/dagobert/issues/35)

### Styling
- [ ] The search bar component needs to be reusable and customizable
- [ ] Search bar needs to be easily integrable within our existing codebase 
- [ ] Component features: Search icon, Placeholder text, Clear icon
- [ ] Search bar has 2 states: default / active
- [ ] The search bar component should match the design system specifications

## Tasks
- [ ] Create a new branch `feature/search-items`
- [ ] Add a search bar to the transactions list view
- [ ] Develop the functionality to filter the expense list in real-time based on user input
- [ ] Implement functionality to reset the transactions list view when the search bar is cleared
- [ ] Implement real-time search with auto-suggestions
- [ ] Ensure the search functionality is not case sensitive
- [ ] Implement logic to ignore white spaces in the search input
- [ ] Implement error handling for the search functionality >> return appropriate error messages for invalid or malformed search queries # # #
