### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by ChristianMoschke** [miToe/dagobert#15]
## Tasks
- [ ] Create a new mongoDB account
- [ ] Create a new database
- [ ] Create a new collection
- [ ] Insert example objects
