### ISSUE TITLE
Buttons UI

### ISSUE THREAD

**Issue by ttnguyen15** [miToe/dagobert#29]
## Description
![Image](https://github.com/miToe/dagobert/assets/164089597/e9225ee3-80b5-4b24-bee1-2f8d4e1235f7)

## Acceptance Criteria
- [ ] The button component needs to be reusable and customizable 
- [ ] Buttons need to be easily integrable within our existing codebase and support various use cases 
- [ ] Buttons need to adhere to our design specifications
- [ ] Component features: Icon + Text label
- [ ] Button variants: primary / secondary
- [ ] Primary specs: 
```
height: 48 px;
background-color: #14B4FF (primary);
color: white;
text-align: center;
```
- [ ] Secondary specs: 
```
height: 48 px;
background-color: #EFF9FF (primary-50);
border: 2px;
border-color: #14B4FF (primary);
color: white;
text-align: center;
```

## Tasks
- [ ] Create feature branch `feature/buttons-ui`
- [ ] Create the basic structure of the `Button` component file
- [ ] Develop the Primary button variant
- [ ] Implement the Secondary button variant
- [ ] Apply design system colors
- [ ] Use the design system typography
- [ ] Ensure correct spacing and padding
- [ ] Apply border and background colors as per design specifications
