### ISSUE TITLE
Colors UI

### ISSUE THREAD

**Issue by ttnguyen15** [miToe/dagobert#30]
## Description

![Image](https://github.com/miToe/dagobert/assets/164089597/095e223b-45c4-4ab9-b2d9-06747bae0dc5)

![Image](https://github.com/miToe/dagobert/assets/164089597/467656c9-c53a-4979-b134-3df502781f35)

## Acceptance Criteria
- [ ] Color palette should include primary, secondary and tertiary colors, as well as neutral colors
- [ ] Primary and secondary colors should have multiple shades (e.g., 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950) to provide flexibility
- [ ] Feedback Colors for Success, Warning and Error 

## Tasks
- [ ] Create feature branch `feature/colors-ui`
- [ ] Implement design colors as above (color palette, neutrals)
- [ ] Implement color variants for primary and secondary colors as above
- [ ] Implement colors for Success, Warning and Error
