### ISSUE TITLE
Checkbox UI

### ISSUE THREAD

**Issue by ttnguyen15** [miToe/dagobert#31]
## Description

![Image](https://github.com/miToe/dagobert/assets/164089597/a0d971a0-0724-4b35-bd94-e7751bacab13)

## Acceptance Criteria
- [ ] Checkbox component needs to be reusable and customizable
- [ ] Checkbox has align with our design system specifications
- [ ] Checkbox has 2 states: default (unchecked) / checked
- [ ] default: `border-color: #B6E6FF (primary/200) `
- [ ] checked: `background-color: 14B4FF (primary);`

## Tasks
- [ ] Create feature branch `feature/checkbox-ui`
- [ ] Create the basic structure of the Checkbox component file
- [ ] Implement the unchecked state
- [ ] Implement the checked state
- [ ] Apply design system colors
