### ISSUE TITLE
Dropdowns UI

### ISSUE THREAD

**Issue by ttnguyen15** [miToe/dagobert#33]
## Description

![Image](https://github.com/miToe/dagobert/assets/164089597/651c9ead-b52b-4853-a152-9676c8614fe3)

## Acceptance Criteria
- [ ] Dropdown needs to be reusable and customizable
- [ ] Dropdown needs to be easily integrable within our existing codebase and support various use cases outlined above
- [ ] Component consists of: Label, Placeholder text, Icon, List of selectable options
- [ ] Dropdown has 5 stages: default, opened + unselected, closed + selected, opened + selected, error
- [ ] Single selections for Transaction type, Currency, Category and Payment method
- [ ] Dropdown component should match the design system specs 

## Tasks
- [ ] Create feature branch `feature/dropdown-ui`
- [ ] Create the basic structure of the Checkbox component file
- [ ] Implement the unchecked state (closed/opened)
- [ ] Implement the checked state (closed/opened)
- [ ] Implement the error state when not selected a required dropdown menu
- [ ] Apply design system colors and font specs according to: https://www.figma.com/design/s2XRDryAXqqMPZbQHfWWK0/budgeting-app?node-id=17-1614
