### ISSUE TITLE
Input field UI

### ISSUE THREAD

**Issue by ttnguyen15** [miToe/dagobert#34]
## Description

![Image](https://github.com/miToe/dagobert/assets/164089597/b19288a2-230d-4a09-b517-85ac29e44952)

## Acceptance Criteria
- [ ] Input field has 2 states: default / filled
- [ ] Input field component consists of: Label, Placeholder text
- [ ] The text input field component should match the design system specifications

## Tasks
- [ ] Create feature branch `feature/inputField-ui`
- [ ] Create the basic structure of the text input field component file
- [ ] Implement the two states of default and filled
- [ ] Implement label and placeholder text 
- [ ] Apply design system colors
