### ISSUE TITLE
Search bar UI

### ISSUE THREAD

**Issue by ttnguyen15** [miToe/dagobert#35]
##Description

![Image](https://github.com/miToe/dagobert/assets/164089597/4a43ae41-21c4-4f1c-b552-03dcced19011)

##Acceptance Criteria

- [ ] The search bar component needs to be reusable and customizable
- [ ] Search bar needs to be easily integrable within our existing codebase 
- [ ] Component features: Search icon, Placeholder text, Clear icon
- [ ] Search bar has 2 states: default / active
- [ ] The search bar component should match the design system specifications

##Tasks

- [ ] Create feature branch `feature/searchBar-ui`
- [ ] Create the basic structure of the Search Bar component file
- [ ] Add a search icon to the input field
- [ ] Add support for Placeholder text (Type to search...)
- [ ] Implement clearable input functionality and display it by adding the clear icon
- [ ] Ensure the search bar has 2 states: default and active
- [ ] Apply design system colors
