### ISSUE TITLE
Transaction list & category icons

### ISSUE THREAD

**Issue by ChristianMoschke** [miToe/dagobert#49]
##Description

![Image](https://github.com/miToe/dagobert/assets/164089597/78dd7760-c30b-4d14-b80e-7d236d8294fd)
![Image](https://github.com/miToe/dagobert/assets/164089597/f0d9aefe-1a26-487b-bc36-58c158240d42)

##Acceptance Criteria

- [ ] The overall looks of the wireframe has been matched
- [ ] Every list item has a respective category icon

##Tasks

- [ ] Create feature branch `styling/transactionList`
- [ ] Create a transaction list style component
- [ ] Apply styling based on wireframe
- [ ] Create a function that adds the respective icon to every list item, based on it's category
