### ISSUE TITLE
Transaction Detail View

### ISSUE THREAD

**Issue by ChristianMoschke** [miToe/dagobert#52]
## Value proposition
**As a user** of the budgeting app
**I want to** view and edit detailed information about a specific transaction
**So that** I can understand my spending habits and manage my budget more effectively

## Description
![Image](https://github.com/miToe/dagobert/assets/164089597/910d924a-14ff-4ffb-b85e-786fabd8501c)

## Acceptance Criteria
- [ ] User should see an overview of the transaction including: Amount, date, transaction category, payment method and description
- [ ] Transaction amount is prominently displayed (expense: negative amount, income: positive amount)
- [ ] Detail page enables users to edit their transaction
- [ ] User can return from detail page to transaction list
- [ ] Detail page looks like wireframe
- [ ] Styling alert and modal

## Tasks
- [ ]  Create feature branch `feature/detail-view`
- [ ]  Display amount, date, transaction category, payment method and description according to the design
- [ ] Implement feature to edit the transaction from the detail view
- [ ] Implement navigation back to Transaction List
- [ ] Style the components to match the design guidelines
