### ISSUE TITLE
Menu (Navigation)

### ISSUE THREAD

**Issue by ttnguyen15** [miToe/dagobert#61]
##Value Proposition
**As a** user 
**I want to** easily navigate within the budget app,
**so that** I can easily access key features fast.

##Description
![Image](https://github.com/miToe/dagobert/assets/164089597/d6db2327-f3f7-4ab7-a531-999898a75a33)

##Acceptance Criteria
- [ ] A navigation bar with links to the home, transaction list, add transactions and reports is displayed at the bottom of the app
- [ ] Users should be able to access any feature of the app from the navigation bar
- [ ] Navigation bar should look like the `wireframe`

## Tasks
- [ ] Create feature branch `feature/navigation`
- [ ] Set up the navigation bar component
- [ ] Develop the navigation bar and ensure it is displayed on all relevant pages
- [ ] Add clickable links to the navigation bar for home, transaction list, add transactions, and reports
- [ ] Set up the routing so that clicking each link directs the user to the appropriate page
- [ ] Style the navigation bar according to the design
