### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by ttnguyen15** [miToe/dagobert#64]
## Description

![Image](https://github.com/miToe/dagobert/assets/164089597/eb547263-919f-4657-912c-e1d2e1f4e265)

## Acceptance Criteria
- [ ] Overview of the user's financial status, including key metrics and visualizations such as total balance, recent transactions and a preview of reports
- [ ]  Dashboard must be accessible from the main interface of the app
- [ ]  Dashboard should adhere to our design specs

## Tasks
- [ ] Create feature branch `feature/dashboard`
- [ ] Develop the frontend components for the dashboard
- [ ] Implement the backend logic to provide data for the dashboard
- [ ] Design the layout and style of the dashboard based on the provided image
