### ISSUE TITLE
Transaction List

### ISSUE THREAD

**Issue by ChristianMoschke** [miToe/dagobert#7]
## Value proposition
As a **budget-conscious user**, 
I want to see **a list of all my recorded expenses**, 
so that I can easily **track my spending and identify areas for improvement in my budget**.
## Description
![Image](https://github.com/miToe/dagobert/assets/164089597/3cd5d255-9fc1-47a4-ae53-c76ec5dd7872)

## Acceptance criteria
- [ ] The list should display all recorded expenses, including date, amount, currency and category.
- [ ] The list should be sorted by date, with the most recent expense at the top.
- [ ] The date should be displayed like this: dd.mm.yyyy

#### The array of objects contains:
- [ ] date
- [ ] amount
- [ ] currency
- [ ] category
- [ ] description
- [ ] paymentMethod

## Tasks
- [ ] Create a feature branch `feature/expense-list`
- [ ] Create a new file `components/TransactionList.js`
- [ ] Import React
- [ ] Create a new variable `transactions` containing an array of objects (examples)
- [ ] Create a new variable `sortedTransactions` to sort the list based on the date
#### Create a new variable which returns:
- [ ] the title `Transactions` inside a `<h1> element`
- [ ] an unordered list - map -> `transactions`
- [ ] a list item, containing `category, date and amount`

- [ ] Import and insert the `TransactionList` component in `pages/index.js` #
