### ISSUE TITLE
Styling form "Add transaction"

### ISSUE THREAD

**Issue by nichoop** [miToe/dagobert#71]
### Description

![Image](https://github.com/miToe/dagobert/assets/164089597/9ec134c3-d9d7-4b5d-ae99-0423b3ad2402)

### Acceptance Criteria
- The form should be styled to be visually consistent with our design.
- The form include labels, drop downs, input fields and buttons to cancel or add
- Error message of required fields is shown when the form is missing input

### Tasks
- [ ] Create branch `feature/styling-form`
- [ ] Style the form
- [ ] Style input fields and labels
- [ ] Make sure the validation for the required fields are working
