### ISSUE TITLE
Expense Detail View

### ISSUE THREAD

**Issue by ChristianMoschke** [miToe/dagobert#8]
## Value proposition
As a **budget-conscious user**, 
I want to see a **detailed view of each expense in my expense list**, 
so that I can **understand the specifics of each transaction and analyze my spending patterns**.
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] Clicking on an expense in the list should open a detailed view of that expense.

#### The detailed view should display all the information associated with the expense, including:

- [ ] Date
- [ ] Amount
- [ ] Category
- [ ] Description (if provided)
- [ ] Payment method (e.g., cash, credit card, PayPal, ApplePay, etc)

## Tasks
- [ ] List the tasks that need to be performed within the dev team # # # # #
