### ISSUE TITLE
Add Transaction

### ISSUE THREAD

**Issue by ChristianMoschke** [miToe/dagobert#9]
## Value Proposition

**As a** budget-conscious user,

**I want to** easily enter details of my expenses as they occur,

**so that** I can accurately track my spending without forgetting or missing out on recording any expenses.

## Description

![Image](https://github.com/miToe/dagobert/assets/164089597/e639f5df-260b-4b87-8943-7631676a4647)

## Acceptance Criteria

- [ ] The user must be able to quickly access the expense entry feature from the main interface of the app.

- [ ] The app should provide a simple and intuitive form for entering expense details, including amount, category (e.g., food, transportation, bills), date, and an optional description.

- [ ] The expense entry form must offer a selection of common expense categories.

- [ ] Has an abort button
- [ ] Has a submit button

## Tasks

- [ ] create feature branch `feature/expense-entry`
- [ ] create a component which returns a `list of transaction categories`
- [ ] create `button` which links to the "add transaction" page
- [ ] create a component which returns a `form to create a transaction `
- [ ] create an `cancel button`
- [ ] create a `submit button` #
